<?php

/**
 * SPARKS Setup Wizard
 * This script initializes the environment, database, and admin user.
 * It will delete itself upon successful completion.
 */

error_reporting(E_ALL);
ini_set('display_errors', 1);

// 1. Initial Checks - Prevent re-running if .env already exists with data
if (file_exists(__DIR__ . '/../.env')) {
    $envLines = file(__DIR__ . '/../.env');
    $hasDb = false;
    foreach ($envLines as $line) {
        if (strpos($line, 'database.default.database') !== false && strpos($line, '=') !== false) {
            $parts = explode('=', $line);
            if (!empty(trim($parts[1]))) {
                $hasDb = true;
                break;
            }
        }
    }
    // If you want to allow re-running for debugging, you can comment this out.
    // if ($hasDb) die("System already configured. Please delete setup.php for security.");
}

// 2. Logic Handling
$error = null;
$success = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $baseUrl   = rtrim($_POST['base_url'], '/') . '/';
    $dbHost    = $_POST['db_host'] ?? '';
    $dbName    = $_POST['db_name'] ?? '';
    $dbUser    = $_POST['db_user'] ?? '';
    $dbPass    = $_POST['db_pass'] ?? '';
    $adminUser = $_POST['admin_user'] ?? '';
    $adminPass = $_POST['admin_pass'] ?? '';
    $workerKey = $_POST['worker_key'] ?? '';

    try {
        // A. Test Connection first
        $mysqli = @new mysqli($dbHost, $dbUser, $dbPass, $dbName);
        if ($mysqli->connect_error) {
            throw new Exception("Database connection failed: " . $mysqli->connect_error);
        }
        $mysqli->close();

        // B. Generate Encryption Key
        $encryptionKey = 'hex2bin:' . bin2hex(random_bytes(32));

        // C. Create .env file
        $envContent = <<<EOD
#--------------------------------------------------------------------
# SPARKS Environment Configuration
# Generated by Setup Wizard - Efesto Tech
#--------------------------------------------------------------------

CI_ENVIRONMENT = production

# APP
app.baseURL = "{$baseUrl}"
app.indexPage = ""

# DATABASE
database.default.hostname = "{$dbHost}"
database.default.database = "{$dbName}"
database.default.username = "{$dbUser}"
database.default.password = "{$dbPass}"
database.default.DBDriver = "MySQLi"
database.default.DBPrefix = ""
database.default.port = "3306"

# ENCRYPTION
encryption.key = "{$encryptionKey}"

# EMAIL QUEUE SYSTEM (EQS) CUSTOM SETTINGS
worker.secret_key = "{$workerKey}"
smtp.encryption_key = "{$encryptionKey}"

# SESSION
session.driver = "CodeIgniter\Session\Handlers\FileHandler"
session.savePath = "writable/session"
EOD;

        if (file_put_contents(__DIR__ . '/../.env', $envContent) === false) {
            throw new Exception("Could not write .env file. Check write permissions on the root folder.");
        }

        // D. Bootstrap CI4 to run migrations
        define('FCPATH', __DIR__ . DIRECTORY_SEPARATOR);
        require_once __DIR__ . '/../app/Config/Paths.php';
        $paths = new \Config\Paths();

        require_once $paths->systemDirectory . '/Boot.php';
        \CodeIgniter\Boot::preload($paths);

        // Explicitly load Common.php if not already loaded (should be by preload)
        if (! function_exists('config')) {
            require_once $paths->systemDirectory . '/Common.php';
        }

        // F. Manually load the newly created .env file
        require_once $paths->systemDirectory . '/Config/DotEnv.php';
        (new \CodeIgniter\Config\DotEnv(realpath(__DIR__ . '/../')))->load();
        // E. Run Migrations
        $runner = \Config\Services::migrations();
        try {
            $runner->latest();
        } catch (\Throwable $e) {
            throw new Exception("Migration Error: " . $e->getMessage());
        }

        // F. Create Admin User
        $db = \Config\Database::connect();
        
        // Check if user already exists
        $userExists = $db->table('users')->where('username', $adminUser)->get()->getRow();
        if (!$userExists) {
            $db->table('users')->insert([
                'username'   => $adminUser,
                'password'   => password_hash($adminPass, PASSWORD_BCRYPT),
                'api_key'    => bin2hex(random_bytes(32)),
                'is_active'  => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ]);
        }

        // G. Run seeders (Settings)
        $seeder = \Config\Database::seeder();
        try {
            $seeder->call('App\Database\Seeds\SettingsSeeder');
        } catch (\Throwable $e) {
            // Ignore if settings already exist
        }

        $success = "The Forge of SPARKS is ready! The setup scroll has been burned for security. Redirecting to login...";
        
        // H. Self-destruct
        unlink(__FILE__);

    } catch (Throwable $e) {
        $error = "The anvil cracked: " . $e->getMessage();
    }
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SPARKS | Setup the Forge</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&family=Inter:wght@300;400;600&display=swap">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <style>
        :root {
            --hephaestus-gold: #c5a021;
            --terracotta: #b3542d;
            --marble: #fcfaf7;
            --stone: #24292e;
        }
        body {
            font-family: 'Inter', sans-serif;
            background-color: var(--stone);
            color: var(--marble);
            padding: 50px 0;
            background-image: url('https://www.transparenttextures.com/patterns/dark-leather.png');
        }
        .setup-card {
            background-color: var(--marble);
            color: var(--stone);
            border-top: 8px solid var(--hephaestus-gold);
            border-bottom: 8px solid var(--terracotta);
            border-radius: 0;
            padding: 40px;
            box-shadow: 0 40px 100px rgba(0,0,0,0.8);
            position: relative;
        }
        .setup-card::after {
            content: "";
            position: absolute;
            top: 0; left: 0; right: 0; height: 10px;
            background: repeating-linear-gradient(90deg, var(--hephaestus-gold) 0, var(--hephaestus-gold) 20px, transparent 20px, transparent 40px);
            opacity: 0.1;
        }
        h1 {
            font-family: 'Cinzel', serif;
            font-weight: 900;
            color: var(--stone);
            text-align: center;
            margin-bottom: 10px;
            letter-spacing: 5px;
        }
        .brand-subtitle {
            text-align: center;
            font-family: 'Cinzel', serif;
            color: var(--terracotta);
            font-weight: 700;
            margin-bottom: 40px;
            text-transform: uppercase;
            font-size: 0.9rem;
        }
        .form-control { border-radius: 0; border: 1px solid #ddd; background: #fff; }
        .form-control:focus { border-color: var(--hephaestus-gold); box-shadow: none; }
        .btn-ignite {
            background-color: var(--terracotta);
            color: white;
            font-family: 'Cinzel', serif;
            font-weight: 700;
            border-radius: 0;
            padding: 15px;
            text-transform: uppercase;
            letter-spacing: 2px;
            border: none;
            width: 100%;
            transition: all 0.3s;
        }
        .btn-ignite:hover {
            background-color: var(--stone);
            color: var(--hephaestus-gold);
            transform: scale(1.02);
        }
        .section-title {
            font-family: 'Cinzel', serif;
            border-bottom: 1px solid #eedec0;
            padding-bottom: 5px;
            margin: 40px 0 20px;
            color: var(--stone);
            font-size: 1.1rem;
            font-weight: 900;
            letter-spacing: 1px;
            display: flex;
            align-items: center;
        }
        .section-title i { margin-right: 10px; color: var(--hephaestus-gold); }
        label { font-weight: 700; font-size: 0.85rem; color: #555; text-transform: uppercase; }
    </style>
</head>
<body>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="setup-card">
                <h1>SPARKS</h1>
                <div class="brand-subtitle">Efesto Tech di Marco Spinelli</div>
                
                <p class="text-center text-muted mb-5">Identify yourself, Architect, as we prepare to ignite the digital furnace.</p>

                <?php if ($error): ?>
                    <div class="alert alert-danger border-0 rounded-0 shadow-sm">
                        <i class="fas fa-exclamation-triangle mr-2"></i> <?= $error ?>
                    </div>
                <?php endif; ?>

                <?php if ($success): ?>
                    <div class="alert alert-success border-0 rounded-0 shadow-sm py-4 text-center">
                        <h4 class="font-weight-bold"><i class="fas fa-fire mr-2"></i> SUCCESS!</h4>
                        <p class="mb-0"><?= $success ?></p>
                        <script>setTimeout(() => { window.location.href = 'admin/login'; }, 4000);</script>
                    </div>
                <?php else: ?>

                <form method="POST">
                    <div class="section-title"><i class="fas fa-map-marker-alt"></i> The Citadel Boundary</div>
                    <div class="form-group">
                        <label>Base URL</label>
                        <input type="url" name="base_url" class="form-control" value="http://<?= $_SERVER['HTTP_HOST'] ?>/" placeholder="https://forge.yourdomain.com/" required>
                        <small class="text-muted">The primary path to your Citadel. Must include trailing slash.</small>
                    </div>

                    <div class="section-title"><i class="fas fa-database"></i> The Vault of Hephaestus</div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Hostname</label>
                                <input type="text" name="db_host" class="form-control" value="localhost" placeholder="localhost" required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Database Name</label>
                                <input type="text" name="db_name" class="form-control" placeholder="sparks_db" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Username</label>
                                <input type="text" name="db_user" class="form-control" placeholder="root" required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Password</label>
                                <input type="password" name="db_pass" class="form-control" placeholder="Leave empty if none">
                            </div>
                        </div>
                    </div>

                    <div class="section-title"><i class="fas fa-user-shield"></i> The Master Blacksmith</div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Guardian Name (Admin)</label>
                                <input type="text" name="admin_user" class="form-control" value="admin" required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Secret Password</label>
                                <input type="password" name="admin_pass" class="form-control" placeholder="Minimum 8 characters" required>
                            </div>
                        </div>
                    </div>

                    <div class="section-title"><i class="fas fa-lock"></i> Forge Protection</div>
                    <div class="form-group">
                        <label>Worker Sigil (Secret Key)</label>
                        <input type="text" name="worker_key" class="form-control" value="<?= bin2hex(random_bytes(10)) ?>" required>
                        <small class="text-muted">Keep this safe. You will need it to command the worker via cron or web.</small>
                    </div>

                    <div class="mt-5">
                        <button type="submit" class="btn btn-ignite">
                            <i class="fas fa-hammer mr-2"></i> Strike the Anvil & Begin
                        </button>
                    </div>
                </form>

                <?php endif; ?>
                
                <div class="text-center mt-5">
                    <img src="https://cdn-icons-png.flaticon.com/512/1271/1271228.png" style="width: 40px; opacity: 0.2; filter: grayscale(1);">
                    <div class="mt-2 small text-muted font-italic">
                        Crafted with pride by Efesto Tech di Marco Spinelli
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js"></script>
</body>
</html>
